apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app
  labels:
    app: task-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-app
  template:
    metadata:
      labels:
        app: task-app
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for MySQL to be ready..."
              while ! nc -z mysql-db 3306; do
                sleep 1
              done
              echo "MySQL is ready!"
      containers:
        - name: task
          image: abdulhaleemsan/task-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: '128Mi' # Guaranteed 128 MB memory
              cpu: '500m' # Guaranteed 50% of a single CPU
            limits:
              memory: '256Mi' # Maximum 256 MB memory
              cpu: '1000m' # Maximum 1 CPU core
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: task-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: task-config
                  key: DB_PORT
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: task-config
                  key: PORT
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: task-config
                  key: NODE_ENV
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: task-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: task-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: task-secrets
                  key: JWT_EXPIRATION
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
