# mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: abdulhaleem
            - name: MYSQL_DATABASE
              value: task
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command:
                - mysqladmin
                - ping
                - -h
                - localhost
                - -u
                - root
                - -pabdulhaleem
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          resources:
            requests:
              memory: '256Mi' # Request 256 MB of memory
              cpu: '250m' # Request 0.25 CPU cores
            limits:
              memory: '512Mi' # Limit to 512 MB of memory
              cpu: '500m' # Limit to 0.5 CPU cores
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
